In [1]:
from preparator import Preparator 
import numpy as np

In [99]:
prep = Preparator()

matrix = prep.stiffnessPreparator(4, 100)

eig = np.linalg.eigvals(matrix)
print(matrix)
print(max(np.abs(eig)) / min(np.abs(eig)))
print(np.allclose(matrix,matrix.T))




[[ 0.49265825 -1.          0.78503109  0.59423334]
 [-1.         -0.04892313  0.06530594 -0.88912434]
 [ 0.78503109  0.06530594 -0.51047953  0.03249062]
 [ 0.59423334 -0.88912434  0.03249062 -0.26488166]]
144.98278239286248
True
